on:
  push:
    branches:
      - 'master'

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    # Add this permissions block
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - uses: 'actions/checkout@v4'

    # Authenticate to Google Cloud using Workload Identity Federation
    - id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        workload_identity_provider: 'projects/951972391035/locations/global/workloadIdentityPools/github-pool/providers/github-id-provider'
        service_account: 'github-action-1045900895@ayush-resume.iam.gserviceaccount.com' # e.g., my-sa@my-project.iam.gserviceaccount.com

    # Now you can run Firebase commands, already authenticated
    - name: 'Deploy to Firebase'
      run: |
        cd resume-app
        npm install -g firebase-tools
        npm install
        npm run build
        firebase login
        firebase deploy
